parameters:
  app.name: Magento 2 Generator
  app.version: 0.1.0

services:
  _defaults:
    autowire: true

  App\:
    resource: '../src/*'

  operation.create_di:
    class: App\Operation\CreateXml
    arguments:
      $file: etc/di.xml
      $xsd: urn:magento:framework:ObjectManager/etc/config.xsd

  operation.create_events:
    class: App\Operation\CreateXml
    arguments:
      $file: etc/events.xml
      $xsd: urn:magento:framework:Event/etc/events.xsd

  command.generate_di:
    class: App\Console\GenerateXmlCommand
    arguments:
      $createXml: '@operation.create_di'
      $name: 'generate:di'
      $file: 'di.xml'

  command.generate_events:
    class: App\Console\GenerateXmlCommand
    arguments:
      $createXml: '@operation.create_events'
      $name: 'generate:events'
      $file: 'events.xml'

  Symfony\Component\Console\Application:
    public: true
    arguments:
      $name: '%app.name%'
      $version: '%app.version%'
    calls:
      - method: addCommands
        arguments:
          $commands:
            - '@App\Console\GenerateModuleCommand'
            - '@command.generate_di'
            - '@command.generate_events'

  Symfony\Component\Filesystem\Filesystem:

  twig.loader:
    class: Twig\Loader\LoaderInterface
    factory: ['@App\Twig\LoaderFactory', 'create']

  Twig\Environment:
    arguments:
      - '@twig.loader'
